kernel:
  image: linuxkit/kernel:4.14.68
  cmdline: "console=ttyS0"

init:
  - linuxkit/init:e24105ebb339e1a2e578fde7ec8bccf844a633d5
  - linuxkit/runc:1dc6559fd0a9a332c740312637af0c3fbe6bafa3
  - linuxkit/containerd:ed0589d53e29890b0e504f594a0e4af7326b6484
  - linuxkit/ca-certificates:v0.6

onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: format
    image: linuxkit/format:v0.6
  - name: mount
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib/docker"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.6

services:
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: sshd
    image: linuxkit/sshd:v0.6
    binds:
     - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  - name: ntpd
    image: linuxkit/openntpd:v0.6
  - name: docker
    image: docker:18.06.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]

files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'

trust:
  org:
    - linuxkit
    - library
