---
version: 0.2

env:
  variables:
    LINUXKIT_SHA256: "4957a1b0357f9d30a297e71ee2ba5c9ddf417428aa0116a4057e10cfd1f75a28"

phases:
  pre_build:
    commands:
      - curl -sOL https://s3.amazonaws.com/agy-public/linuxkit
      - echo "${LINUXKIT_SHA256}" linuxkit | sha256sum -c -
      - install --mode 0755 linuxkit /usr/bin/linuxkit && rm -f linuxkit

  build:
    commands:
      - linuxkit build -size 512M -format aws aws.yml

artifacts:
  files:
    - aws.raw
